language: node_js
node_js:
  - node

cache: yarn

branches:
  only:
    - master

before_deploy:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master
